categories/urls.py
from .views import *
from django.urls import path

app_name = 'categories'

urlpatterns = [
    path('', view_categories, name='view-categories'),
    path('cat/create/', cat_create, name='cat-create'),
    path('subcat/create/', subcat_create, name='subcat-create'),

]

sim/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, login_view, logout_view, auth_view

urlpatterns = [
    path('assets/', include('assets.urls')),
    path('custodians/', include('custodians.urls')),
    path('reports/', include('history.urls')),
    path('allocations/', include('allocations.urls')),
    path('disposals/', include('disposals.urls')),
    path('categories/', include('categories.urls')),

    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('auth_error', auth_view, name='auth-error')
]

categories/models.py
from django.db import models
from django.urls import reverse


class Category (models.Model):
    name = models.CharField(max_length=25)

    def get_absolute_url(self):
        return reverse("categories:cat-update", kwargs={"id":self.id})

class SubCategory (models.Model):
    name = models.CharField(max_length=40)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    depreciation_length = models.IntegerField()

    def get_absolute_url(self):
        return reverse("categories:subcat-update", kwargs={"id":self.id})

categories/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Category, SubCategory
from pages.decorators import allowed_users


@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer', 'logassistant'])
def view_categories(request):
    queryset = SubCategory.objects.all().order_by('category')
    context = {
        "object_list": queryset
    }
    return render(request, "view_categories.html", context)

# Category Views
@login_required(login_url='login')
@allowed_users(allowed_roles=['logco'])
def cat_create(request):
    if request.method == "POST":
        c_name = request.POST.get('name')
        new = Category.objects.create(name=c_name)

        return redirect("/categories/", {})

    return render(request, "create_cat.html", {})
@login_required(login_url='login')
@allowed_users(allowed_roles=['logco'])
def cat_update(request, id):
    if request.method == "GET":
        obj = get_object_or_404(Category, id=id)
        context = {
            "object": obj
        }
        return render(request, "update_cat.html", context)

    if request.method == "POST":
        obj2 = get_object_or_404(Category, id=id)

        obj2.name = request.POST.get('name')
        obj2.save()

        return redirect("/categories/", {})


@login_required(login_url='login')
@allowed_users(allowed_roles=['logco'])
def subcat_create(request):
    if request.method == "GET":
        queryset = Category.objects.all()
        context = {
            "object_list": queryset
        }
        return render(request, "create_subcat.html", context)
    if request.method == "POST":
        c_name = request.POST.get('name')
        c_depreciation = request.POST.get('depreciation')

        data = request.POST.get('category')
        c_category = Category.objects.get(id=data)
        print(request.POST)

        new = SubCategory.objects.create(name=c_name, category= c_category, depreciation_length=c_depreciation)

        return redirect("/categories/", {})


@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer'])
def subcat_update(request, id):
    if request.method == "GET":
        obj = get_object_or_404(SubCategory, id=id)
        queryset = Category.objects.all()
        context = {
            "object": obj,
            "object-list": queryset
        }
        return render(request, "update_subcat.html", context)

    if request.method == "POST":
        obj2 = get_object_or_404(SubCategory, id=id)

        obj2.name = request.POST.get('name')
        obj2.depraciation_length = request.POST.get('depreciation')

        data = request.POST.get('category')
        obj.category = Category.objects.get(id=data)
        obj2.save()

        return redirect("/categories/", {})



@login_required(login_url='login')
@allowed_users(allowed_roles=['logco'])
def subcat_delete(request, custodian_id):
    obj = get_object_or_404(Category, id=custodian_id)
    obj.delete()

    return redirect("/custodians/", {})

categories/templates/create_cat.html
{% extends 'base.html' %}

{% block content %}
<div class="cust-select">
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label>Category Name</label>
            <input name="name" class="form-control form-control-sm" type="text" placeholder="Enter Name Here">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>



{% endblock %}

categories/templates/create_subcat.html
{% extends 'base.html' %}

{% block content %}
<div class="cust-select">
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label>Sub-Category Name</label>
            <input name="name" class="form-control form-control-sm" type="text" placeholder="Enter Name Here">
        </div>
        <div class="form-group">
            <div class="cust-select">
                <label>Parent Category</label>
                <select id="" name="category" class="form-control selectpicker" data-live-search="true" searchable="Select Category">
                    {% for instance in object_list %}
                    <option data-tokens="{{instance.name}}" value="{{ instance.id }}">{{instance.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group">
            <label>Useful Life</label>
            <input name="depreciation" class="form-control form-control-sm" type="text" placeholder="ex: 36">
            <small class="form-text text-muted">Enter useful life in months for this sub-category</small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

{% endblock %}

categories/templates/view_categories.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'categories:cat-create' %}" class="btn btn-warning"> Create Category </a>
<a href="{% url 'categories:subcat-create' %}" class="btn btn-warning"> Create Sub-Category </a>

<div class="list-info">
    <h1> List of Categories and Subcategories</h1>
    <p>- Categories can and subcategories can be created here via this page</p>
    <p>- Create the category first and sub-category later due to parent-child relation</p>
    <p>- Deletions must be made through admin panel</p>
</div>

    <div class="narrow-table">
        <table class="ui selectable celled striped table" id="mainTable">
          <thead>
            <tr>
              <th>Category</th>
              <th>Sub-Category</th>
              <th>Useful Lifetime</th>
            </tr>

          </thead>
          <tbody>
            {% for instance in object_list %}
            <tr>
              <td>{{ instance.category.name }}</td>
              <td>{{ instance.name }}</td>
              <td>{{ instance.depreciation_length}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}

{% load static %}
{% block scripts %}

<!--    Customization JS for table search-->
    <script src='{% static "js/tablesearch.js" %}'></script>
    <script src='{% static "js/table.js" %}'></script>

    <link rel="stylesheet" type="text/css" href="{% static "css/datatables.min.css" %}"/>
    <script src='{% static "js/datatables.min.js" %}'></script>


{% endblock %}