custodians/urls.py
from django.urls import path
from .views import *

app_name = 'custodians'

urlpatterns = [
    path('', view_custodians, name='view_custodians'),
    path('<int:custodian_id>/', custodian_details, name='custodian-detail'),
    path('create/', custodian_create, name='create'),
    path('<int:custodian_id>/update', custodian_update, name='custodian-update'),
    path('<int:custodian_id>/delete', custodian_delete, name='custodian-delete')
]

history/urls.py
from django.urls import path
from history.views import *

app_name = 'reports'
urlpatterns = [
    path('', reports_main, name='reports-main'),
    path('asset/', generate_asset, name='generate-asset'),
    path('custodian/', generate_custodian, name='generate-asset'),
    path('custodian/<int:custodian_id>/', report_custodian, name='report-custodian'),
    path('asset/<int:asset_id>/', report_asset, name='report-asset'),
]

sim/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, login_view, logout_view, auth_view

urlpatterns = [
    path('assets/', include('assets.urls')),
    path('custodians/', include('custodians.urls')),
    path('reports/', include('history.urls')),
    path('allocations/', include('allocations.urls')),
    path('disposals/', include('disposals.urls')),
    path('categories/', include('categories.urls')),

    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('auth_error', auth_view, name='auth-error')
]

custodians/models.py
from django.db import models
from django.urls import reverse


class Custodian(models.Model):
    name = models.CharField(max_length=50)
    position = models.CharField(max_length=50)
    base = models.CharField(max_length=10, default="ERB")

    #To retun name instead od ID number when refered in other areas
    # def __str__(self):
    #     return self.name

    def get_absolute_url(self):
        return reverse("custodians:custodian-detail", kwargs={"custodian_id":self.id})

# Create your models here.

custodians/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Custodian
from pages.decorators import allowed_users

# Create your views here.
@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer', 'logassistant'])
def view_custodians(request):
    queryset = Custodian.objects.all();
    context = {
        "object_list": queryset
    }
    return render(request, "view_custodians.html", context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer', 'logassistant'])
def custodian_details(request, custodian_id):
    obj = get_object_or_404(Custodian, id=custodian_id)
    context = {
        "object": obj
    }
    return render(request, "custodian_details.html", context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer'])
def custodian_create(request):
    if request.method == "GET":
        return render(request, "create.html", {})
    if request.method == "POST":
        c_name = request.POST.get('name')
        c_position = request.POST.get('position')
        c_base = request.POST.get('base')

        new = Custodian.objects.create(name=c_name, position=c_position, base=c_base)

        return redirect("/custodians/", {})

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer'])
def custodian_update(request, custodian_id):
    if request.method == "GET":
        obj = get_object_or_404(Custodian, id=custodian_id)
        context = {
            "object": obj
        }
        return render(request, "update_cust.html", context)

    if request.method == "POST":
        obj2 = get_object_or_404(Custodian, id=custodian_id)
        
        obj2.name = request.POST.get('name')
        obj2.position = request.POST.get('position')
        obj2.base = request.POST.get('base')
        obj2.save()
        return redirect("/custodians/", {})

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager'])
def custodian_delete(request,custodian_id):
    obj = get_object_or_404(Custodian, id=custodian_id)
    obj.delete()

    return redirect("/custodians/", {})

custodians/templates/create.html
{% extends 'base.html' %}

{% block content %}
<div class="cust-select">
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label>Name - Last Name</label>
            <input name="name" class="form-control form-control-sm" type="text" placeholder="Enter Full Name Here">
        </div>
        <div class="form-group">
            <label>Position</label>
            <input name="position" class="form-control form-control-sm" type="text" placeholder="Enter Position Here">
        </div>
        <div class="form-group">
            <label>Base</label>
            <input name="base" class="form-control form-control-sm" type="text" placeholder="ex: ERB">
            <small class="form-text text-muted">Use three digit BASE code as given in the example</small>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>

{% endblock %}

custodians/templates/custodian_details.html
{% extends 'base.html' %}

{% block content %}

<div class="details">
   <h4>Name: {{ object.name }}</h4>
    <p></p>
    <h4>Position: {{ object.position }}</h4>
    <p></p>
    <h4>Base: {{ object.base }}</h4>
    <p></p>
</div>
<a href="{% url 'custodians:custodian-update' object.id %}" type="button" class="btn btn-primary">Update</a>
<a href="{% url 'reports:report-custodian' object.id %}" type="button" class="btn btn-warning">Generate Custodian Report</a>
<button type="button"  data-toggle="modal" data-target="#deleteModel" class="btn btn-danger" >Delete</button>



<!-- Modal for Delete Validation -->
<div class="modal fade" id="deleteModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">WARNING !!</h4>
      </div>
      <div class="modal-body">
          Are you sure you want to delete this item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'custodians:custodian-delete' object.id %}" type="submit" class="btn btn-danger">Yes!</a>
      </div>
    </div>
  </div>
</div>



{% endblock %}

custodians/templates/update_cust.html
{% extends 'base.html' %}

{% block content %}
<div class="cust-select">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
            <label>Name - Last Name</label>
            <input name="name" class="form-control form-control-sm" type="text" placeholder="Enter Full Name Here" value="{{ object.name }}">
        </div>
        <div class="form-group">
            <label>Position</label>
            <input name="position" class="form-control form-control-sm" type="text" placeholder="Enter Position Here" value="{{ object.position }}">
        </div>
        <div class="form-group">
            <label>Base</label>
            <input name="base" class="form-control form-control-sm" type="text"  value="{{ object.base }}">
            <small class="form-text text-muted">Use three digit BASE code as given in the example</small>
        </div>
        <input type="submit" class="btn btn-primary" value="Update">
        <a href="{% url 'custodians:custodian-detail' object.id %}" type="submit" class="btn btn-warning">Cancel</a>
        <button type="button"  data-toggle="modal" data-target="#deleteModel" class="btn btn-danger" >Delete</button>
    </form>
</div>

<!-- Modal for Delete Validation -->
<div class="modal fade" id="deleteModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">WARNING !!</h4>
      </div>
      <div class="modal-body">
          Are you sure you want to delete this item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'custodians:custodian-delete' object.id %}" type="submit" class="btn btn-danger">Yes!</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

custodians/templates/view_custodians.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'custodians:create' %}" class="btn btn-warning"> Create User </a>
<h1> List of Users</h1>

    <div class="narrow-table">
        <table class="ui selectable celled striped table" id="mainTable">
          <thead>
            <tr>
              <th>Base</th>
              <th>User Name</th>
              <th>Position</th>
            </tr>

          </thead>
          <tbody>
            {% for instance in object_list %}
            <tr>
              <td>{{ instance.base }}</td>
              <td class="selectable"><a href="{{ instance.get_absolute_url }}">{{ instance.name }}</a></td>
              <td>{{ instance.position }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
{% endblock %}

{% load static %}
{% block scripts %}

<!--    Customization JS for table search-->
    <script src='{% static "js/tablesearch.js" %}'></script>
    <script src='{% static "js/table.js" %}'></script>

    <link rel="stylesheet" type="text/css" href="{% static "css/datatables.min.css" %}"/>
    <script src='{% static "js/datatables.min.js" %}'></script>


{% endblock %}