assets/urls.py
from django.urls import path
from assets.views import list_view, detail_view, create_view, assign_view, update_view, delete_view

app_name = 'assets'
urlpatterns = [
    path('list_view/', list_view, name='list-view'),
    path('<int:asset_id>/', detail_view, name='asset-detail'),
    path('<int:asset_id>/update/', update_view, name='asset-update'),
    path('create/', create_view, name='asset-create'),
    path('<int:asset_id>/delete/', delete_view, name='asset-delete'),
    path('<int:asset_id>/assign/', assign_view, name='asset-assign'),
]

history/urls.py
from django.urls import path
from history.views import *

app_name = 'reports'
urlpatterns = [
    path('', reports_main, name='reports-main'),
    path('asset/', generate_asset, name='generate-asset'),
    path('custodian/', generate_custodian, name='generate-asset'),
    path('custodian/<int:custodian_id>/', report_custodian, name='report-custodian'),
    path('asset/<int:asset_id>/', report_asset, name='report-asset'),
]

sim/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, login_view, logout_view, auth_view

urlpatterns = [
    path('assets/', include('assets.urls')),
    path('custodians/', include('custodians.urls')),
    path('reports/', include('history.urls')),
    path('allocations/', include('allocations.urls')),
    path('disposals/', include('disposals.urls')),
    path('categories/', include('categories.urls')),

    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('auth_error', auth_view, name='auth-error')
]

assets/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from decimal import Decimal

from custodians.models import Custodian
from categories.models import SubCategory


class Asset(models.Model):
    #Asset Details
    tag_number = models.CharField(max_length=18)
    brand = models.CharField(max_length=50, default="")
    model = models.CharField(max_length=100, default="")
    serial = models.CharField(max_length=40, default="")
    sub_category = models.ForeignKey(SubCategory, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.CharField(max_length=120)

    #User and Location Details
    location = models.CharField(max_length=20, default="")
    physical_location = models.CharField (max_length=80, default="")
    condition = models.CharField(max_length=40, default="")
    custodian = models.ForeignKey(Custodian, blank=True, null=True, on_delete=models.CASCADE)
    accessories = models.CharField(max_length=140, default="")

    #Purchase Details
    price = models.DecimalField(decimal_places=2, max_digits=8, default=123)
    donor = models.CharField(max_length=25, default="")
    budgetCode = models.CharField(max_length=25, default="")
    purchaseReference = models.CharField(max_length=45, default="")
    purchaseDate = models.DateField(auto_now=False, auto_now_add=False, default=date.today)
    supplierName = models.CharField(max_length=80, default="2")

    #Other

    comments = models.CharField(max_length=140, default="")


    def get_absolute_url(self):
        return reverse("assets:asset-detail", kwargs={"asset_id":self.id})

    def depreciation(self):
        d1 = self.purchaseDate
        d2 = date.today()
        # Calculate the number of months
        months = (d2.year - d1.year)*12 +(d2.month-d1.month)
        #Calculate the amount of total depreciation
        reduction = self.price*Decimal(months/self.sub_category.depreciation_length)

        result = round(self.price - reduction, 2)

        if result > 0:
            return result

    def is_allocated(self):
        y = "Yes"
        n = "No"
        val = self.allocation_set.all()

        if val.exists():
            return y
        else:
            return n

    def is_disposed(self):
        y = "Yes"
        n = "No"
        val = self.disposal_set.all()
        if val.exists():
            return y
        else:
            return n




# Create your models here.

assets/forms.py
from django import forms

from .models import Asset
from custodians.models import Custodian
from categories.models import SubCategory

class AssetForm(forms.ModelForm):
    custodian = forms.ModelChoiceField(queryset=Custodian.objects.all(),
                                       to_field_name='name',
                                       empty_label="Select Custodian")
    sub_category = forms.ModelChoiceField(queryset= SubCategory.objects.all(),
                                         to_field_name='name',
                                         empty_label="Select Sub Category")

    class Meta:
        model = Asset
        fields = [
            'tag_number',
            'brand',
            'model',
            'serial',
            'sub_category',
            'description',
            'price',
            'location',
            'physical_location',
            'condition',
            'accessories',
            'price',
            'donor',
            'budgetCode',
            'purchaseReference',
            'purchaseDate',
            'supplierName',
            'comments',
        ]

#Forms to assign assets to custodians
class AssignForm(forms.ModelForm):

    custodian = forms.ModelChoiceField(queryset=Custodian.objects.all(),
                                       to_field_name='name',
                                       empty_label="Select Custodian")
    class Meta:
        model = Asset
        fields = [
            'custodian'
        ]


# class RawProductForm(forms.Form):
#     title = forms.CharField()
#     details = forms.CharField()
#     price = forms.DecimalField()
#     custodian = forms.IntegerField

assets/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import UpdateView
from django.contrib.auth.decorators import login_required
from datetime import date

from .models import Asset
from history.models import History
from custodians.models import Custodian
from categories.models import SubCategory, Category
from allocations.models import Allocation

# from .forms import AssetForm, AssignForm
from pages.decorators import allowed_users

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer', 'logassistant'])
def list_view(request):

    queryset = reversed(Asset.objects.all())
    context = {
        "object_list": queryset
    }
    return render(request, "list_view.html", context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer', 'logassistant'])
def detail_view(request,asset_id):
    #Show method if exists:
    obj = get_object_or_404(Asset, id=asset_id)
    queryset = reversed(Allocation.objects.filter(assets=asset_id))

    context = {
        "object": obj,
        "object_list": queryset
    }
    return render(request, "asset_details.html", context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer'])
def create_view(request):
    if request.method == "GET":
        queryset = SubCategory.objects.all()
        context ={
            "object": queryset
        }
        return render(request, "asset_create.html", context)
    if request.method == "POST":
        #Asset info
        c_tag = request.POST.get('tag_number')
        c_brand = request.POST.get('brand')
        c_model = request.POST.get('model')
        c_serial = request.POST.get('serial')
        c_description = request.POST.get('description')
        data = request.POST.get('sub_cat')
        c_sub_cat = SubCategory.objects.get(id=data)
        #User info
        c_location = request.POST.get('location')
        c_physical_location = request.POST.get('physical_location')
        c_condition = request.POST.get('condition')
        c_accessories = request.POST.get('accessories')
        #Purchase Info
        c_purchaseReferece = request.POST.get('purchaseReference')
        c_purchaseDate = request.POST.get('purchaseDate')
        c_price = request.POST.get('price')
        c_donor = request.POST.get('donor')
        c_budgetCode = request.POST.get('budgetCode')
        c_supplierName = request.POST.get('supplierName')
        c_comments = request.POST.get('comments')

        # Create Code
        new = Asset.objects.create(tag_number=c_tag,
                                   brand = c_brand,
                                   model = c_model,
                                   serial = c_serial,
                                   sub_category = c_sub_cat,
                                   description = c_description,
                                   price = c_price,
                                   location = c_location,
                                   physical_location = c_physical_location,
                                   condition = c_condition,
                                   accessories = c_accessories,
                                   donor = c_donor,
                                   budgetCode = c_budgetCode,
                                   purchaseReference = c_purchaseReferece,
                                   purchaseDate = c_purchaseDate,
                                   supplierName = c_supplierName,
                                   comments = c_comments)
        return redirect("/assets/list_view/", {})

@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer'])
def update_view(request, asset_id):

    if request.method == 'POST':
        obj = get_object_or_404(Asset, id=asset_id)
        # Asset info
        obj.tag = request.POST.get('tag_number')
        obj.brand = request.POST.get('brand')
        obj.model = request.POST.get('model')
        obj.serial = request.POST.get('serial')
        obj.description = request.POST.get('description')
        data = request.POST.get('sub_cat')
        obj.sub_category = SubCategory.objects.get(id=data)
        # User info
        obj.location = request.POST.get('location')
        obj.physical_location = request.POST.get('physical_location')
        obj.condition = request.POST.get('condition')
        obj.accessories = request.POST.get('accessories')
        # Purchase Info
        obj.purchaseReferece = request.POST.get('purchaseReference')
        obj.purchaseDate = request.POST.get('purchaseDate')
        obj.price = request.POST.get('price')
        obj.donor = request.POST.get('donor')
        obj.budgetCode = request.POST.get('budgetCode')
        obj.supplierName = request.POST.get('supplierName')
        obj.comments = request.POST.get('comments')

        data = request.POST.get('custodian')
        # gets "custodian_id" from post data
        obj.custodian = Custodian.objects.get(id=data)
        # gets "custodian"

        obj.save()


        return redirect('assets:asset-detail', asset_id=asset_id)

    asset = get_object_or_404(Asset, id=asset_id)
    obj2 = Custodian.objects.all()
    obj3 = SubCategory.objects.all()
    context = {
        "object": asset,
        "custodian": obj2,
        "subcategory": obj3
    }
    return render(request, "asset_update.html", context)



@login_required(login_url='login')
@allowed_users(allowed_roles=['logco', 'logmanager', 'logofficer', 'logassistant'])
def assign_view(request, asset_id):

    # gets the values of the URL
    if request.method == "GET":
        obj = get_object_or_404(Asset, id=asset_id)
        obj2 = Custodian.objects.all()
        context = {
            "object": obj,
            "custodian": obj2
        }
        return render(request, "asset_assign.html", context)

    # for posting the values of the URL
    if request.method == "POST":
        a_id = get_object_or_404(Asset, id=asset_id)
        a_id.location = request.POST.get('location')
        a_id.physical_location = request.POST.get('physical_location')
        a_id.comments = request.POST.get('comments')
        #gets "asset"
        data = request.POST.get('custodian')
        #gets "custodian_id" from post data
        c_id = Custodian.objects.get(id=data)
        #gets "custodian"

        a_id.custodian = c_id                           #assigns id field of custodian to the asset's field
        a_id.save()

        ret = History.objects.create(asset_id=a_id, custodian_id=c_id) #creates history of the assignment

        return redirect('assets:asset-detail', asset_id=asset_id)




@login_required(login_url='login')
@allowed_users(allowed_roles=['logco'])
def delete_view(request,product_id):
    #Show method if exists:
    obj = Asset.objects.get(id=product_id)
    #delete method:
    obj.delete()
    context = {
    }
    return render(request, "delete_view.html", context)



# Create your views here.

assets/templates/asset_assign.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h2>Asset Assign {{ object.tag_number }}</h2>
    <div class="container">
        <div class="row">
            <form method="POST", action=".">
                {% csrf_token %}
                <div class="col-sm-6 create-view">
                    <div class="form-group ">
                        <h4> Asset Information </h4>
                        <label>Tag Number</label>
                        <p>{{ object.tag_number }}</p>
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <p>{{ object.description }}</p>
                    </div>
                    <div class="cust-select">
                        <label>Select User:</label>
                        <select id="custodian" name="custodian" class="form-control selectpicker" data-live-search="true" searchable="Current Custodian {{ object.custodian.name }}">
                            <option value="" disabled selected>Current Custodian {{ object.custodian.name }}</option>
                            {% for instance in custodian %}
                            <option data-tokens="{{instance.name}}" value="{{ instance.id }}">{{instance.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-sm-6 create-view">
                    <div class="form-group">
                        <h4> Other Information </h4>
                        <label>Location</label>
                        <input name="location" class="form-control form-control-sm" type="text" placeholder="Enter Base Location" value="{{object.location}}">
                        <small class="form-text text-muted">3 digit base code. Ex: ERB</small>
                    </div>
                    <div class="form-group">
                        <label>Physical Location</label>
                        <input name="physical_location" class="form-control form-control-sm" type="text" placeholder="Enter physical location" value="{{object.physical_location}}">
                        <small class="form-text text-muted">Ex: WASH Office 1 or Drivers Room</small>
                    </div>
                    <div class="form-group">
                            <label>Comments</label>
                            <textarea name="comments" class="form-control" rows="3">{{object.comments}}</textarea>
                        </div>
                </div>
        </div>
    </div>
    <input class="btn btn-primary" type="submit" value='Save' />
        </form>
</div>

{% endblock %}

assets/templates/asset_create.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>Create Asset</h2>
    <p>Make sure all required information is filled before you submit</p>
    <form method="POST" action=".">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm-6 create-view">
                    <div class="form-group ">
                        <h4> Asset Information </h4>
                        <label>Tag Number</label>
                        <input name="tag_number" class="form-control form-control-sm" type="text" placeholder="CCC/YY/DDD">
                        <small class="form-text text-muted">Use the format in ex: IRQ/YY/100</small>
                    </div>
                    <div class="form-group">
                        <label>Brand</label>
                        <input name="brand" class="form-control form-control-sm" type="text" placeholder="Enter brand Here">
                    </div>
                    <div class="form-group">
                        <label>Model</label>
                        <input name="model" class="form-control form-control-sm" type="text" placeholder="Enter model here">
                    </div>
                    <div class="form-group">
                        <label>Serial Number</label>
                        <input name="serial" class="form-control form-control-sm" type="text" placeholder="Enter serial #">
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <input name="description" class="form-control form-control-sm" type="text" placeholder="Enter description here">
                    </div>
                    <div class="cust-select">
                        <label>Sub-Category</label>
                        <select id="" name="sub_cat" class="form-control selectpicker" data-live-search="true" searchable="Select Sub-Category">
                            {% for instance in object %}
                            <option data-tokens="{{instance.name}}" value="{{ instance.id }}">{{instance.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <p></p>
                </div>
                <div class="col-sm-6 create-view">
                    <h4> Location Information </h4>
                    <div class="form-group">
                        <label>Location</label>
                        <input name="location" class="form-control form-control-sm" type="text" placeholder="Enter Base Location">
                        <small class="form-text text-muted">3 digit base code. Ex: ERB</small>
                    </div>
                    <div class="form-group">
                        <label>Physical Location</label>
                        <input name="physical_location" class="form-control form-control-sm" type="text" placeholder="Enter physical location">
                        <small class="form-text text-muted">Ex: WASH Office 1 or Drivers Room</small>
                    </div>
                    <div class="form-group">
                        <label>Condition</label>
                        <select name="condition" class="form-control" id="exampleFormControlSelect1">
                            <option>Good</option>
                            <option>Broken</option>
                            <option>Maintenance</option>
                            <option>Lost</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Accessories</label>
                        <input name="accessories" class="form-control form-control-sm" type="text" placeholder="Enter list of accessories">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 create-view">
                    <h4> Purchase Information </h4>
                    <div class="form-group">
                        <label>Purchase File Reference</label>
                        <input name="purchaseReference" class="form-control form-control-sm" type="text" placeholder="Enter list of accessories">
                    </div>
                    <div class="form-group">
                        <label>Invoice Date</label>
                        <div class="input-group date" data-date-format="yyyy-mm-dd">
                            <input name="purchaseDate" type="text" class="form-control" placeholder="dd.mm.yyyy">
                            <div class="input-group-addon" >
                                <span class="glyphicon glyphicon-th"></span>
                            </div>
                        </div>
                        <p></p>
                        <div class="form-group">
                            <label>Price</label>
                            <input name="price" class="form-control form-control-sm" type="number" placeholder="Price in USD">
                        </div>
                        <div class="form-group">
                            <label>Supplier's Name</label>
                            <input name="supplierName" class="form-control form-control-sm" type="text" placeholder="">
                        </div>
                </div>
            </div>
                <div class="col-sm-6 create-view">
                    <div class="form-group">
                            <h4> Donor Information </h4>
                            <label>Donor</label>
                            <input name="donor" class="form-control form-control-sm" type="text" placeholder="">
                        </div>
                        <div class="form-group">
                            <label>Budget Code</label>
                            <input name="budgetCode" class="form-control form-control-sm" type="text" placeholder="">
                        </div>
                        <div class="form-group">
                            <label>Comments</label>
                            <textarea name="comments" class="form-control" rows="3"></textarea>
                        </div>
                </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
        <a href="{% url 'assets:list-view' %}" type="submit" class="btn btn-danger">Cancel</a>
    </form>
</div>



{% endblock %}

{% load static %}
{% block scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <script src='{% static "js/datepicker.js" %}'></script>

{% endblock %}

assets/templates/asset_details.html
{% extends 'base.html' %}

{% block content %}
<div>
    <a href="{% url 'assets:asset-update' object.id %}" type="button" class="btn btn-primary">Update</a>
    <a href="{% url 'assets:asset-assign' object.id %}" type="button" class="btn btn-primary button-assign">Assign</a>
    <a href="{% url 'reports:report-asset' object.id %}" type="button" class="btn btn-warning">Generate Asset Report</a>
    <button type="button"  data-toggle="modal" data-target="#deleteModel" class="btn btn-danger">Delete</button>
    <h2>Asset Details for {{ object.tag_number }}</h2>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 create-view">
                    <div class="form-group ">
                        <h4> Asset Information </h4>
                        <label>Tag Number</label>
                        <p>{{ object.tag_number }}</p>
                    </div>
                    <div class="form-group">
                        <label>Brand</label>
                        <p>{{ object.brand}}</p>
                    </div>
                    <div class="form-group">
                        <label>Model</label>
                        <p>{{ object.model}}</p>
                    </div>
                    <div class="form-group">
                        <label>Serial Number</label>
                        <p>{{ object.serial}}</p>
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        <p>{{ object.description}}</p>
                    </div>
                    <div class="form-group">
                        <label>Category</label>
                        <p>{{ object.sub_category.category.name}}</p>
                    </div>
                    <div class="form-group">
                        <label>Sub-Category</label>
                        <p>{{ object.sub_category.name}}</p>
                    </div>
                </div>
                <div class="col-sm-6 create-view">
                    <h4> User & Location Information </h4>
                    <div class="form-group">
                        <label>User</label>
                        <p>{{ object.custodian.name}}</p>
                    </div>
                    <div class="form-group">
                        <label>Location</label>
                        <p>{{ object.location}}</p>
                    </div>
                    <div class="form-group">
                        <label>Physical Location</label>
                        <p>{{ object.physical_location}}</p>
                    </div>
                    <div class="form-group">
                        <label>Condition</label>
                        <p>{{ object.condition}}</p>
                    </div>
                    <div class="form-group">
                        <label>Accessories</label>
                        <p>{{ object.accessories}}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 create-view">
                    <h4> Purchase Information </h4>
                    <div class="form-group">
                        <label>Purchase File Reference</label>
                        <p>{{ object.purchaseReference}}</p>
                    </div>
                    <div class="form-group">
                        <label>Invoice Date</label>
                        <p>{{ object.purchaseDate}}</p>
                        <p></p>
                        <div class="form-group">
                            <label>Price</label>
                            <p>{{ object.price}}</p>
                        </div>
                        <div class="form-group">
                            <label>Supplier's Name</label>
                            <p>{{ object.supplierName}}</p>
                        </div>
                </div>
            </div>
                <div class="col-sm-6 create-view">
                    <div class="form-group">
                            <h4> Donor Information </h4>
                            <label>Donor</label>
                            <p>{{ object.donor}}</p>
                        </div>
                        <div class="form-group">
                            <label>Budget Code</label>
                            <p>{{ object.budgetCode}}</p>
                        </div>
                        <div class="form-group">
                            <label>Comments</label>
                            <p>{{ object.comments}}</p>
                        </div>
                        <div class="form-group">
                            <label>Current Value (Depreciated)</label>
                            <p>{{ object.depreciation}}</p>
                        </div>
                </div>
            </div>

        </div>
        <div class="allocation-table">
            <h4>List of Allocations</h4>
            <div class="narrow-table">
                <table class="ui selectable celled striped table" id="mainTable">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Document Number</th>
                        <th>Previous Donor</th>
                        <th>Previous Budget Code</th>
                        <th>New Donor</th>
                        <th>New Budget Code</th>
                        <th>Comments</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for instance in object_list %}
                    <tr>
                        <td>{{ instance.date }}</td>
                        <td class="selectable"><a href="{{ instance.get_absolute_url }}">{{ instance.documentNumber }}</a></td>
                        <td>{{ instance.previousDonor }}</td>
                        <td>{{ instance.previousBudget }}</td>
                        <td>{{ instance.newDonor}}</td>
                        <td>{{ instance.newBudget}}</td>
                        <td>{{ instance.comments}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
             </div>
        </div>
</div>

<!-- Modal for Delete Validation -->
<div class="modal fade" id="deleteModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">WARNING !!</h4>
      </div>
      <div class="modal-body">
          Are you sure you want to delete this item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="{% url 'assets:asset-delete' object.id %}" type="submit" class="btn btn-danger">Yes!</a>
      </div>
    </div>
  </div>
</div>


{% endblock %}